version: '3.8'
services:
  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    container_name: my-mongodb  # Name of the container
    ports:
      - '27017:27017'  # Expose MongoDB on localhost:27017
    volumes:
      - ./data/db:/data/db  # Persist data in a local directory
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Root username
      MONGO_INITDB_ROOT_PASSWORD: example  # Root password
